name: faststream-example

services:

  redis:
    container_name: "${COMPOSE_PROJECT_NAME}-redis"
    image: redis

  consumer:
    container_name: "${COMPOSE_PROJECT_NAME}-consumer"
    build:
      dockerfile: Dockerfile
    depends_on:
      - redis
    entrypoint: python3 -m src.consumer

  producer:
    container_name: "${COMPOSE_PROJECT_NAME}-producer"
    build:
      dockerfile: Dockerfile
    depends_on:
      - consumer
    entrypoint: python3 -m src.producer

