name: faststream-example

services:

  redis:
    image: redis

  consumer:
    build:
      dockerfile: Dockerfile
    environment:
      REDIS_URL: "redis://redis"
    depends_on:
      - redis
    entrypoint: python3 consumer.py

  producer:
    build:
      dockerfile: Dockerfile
    environment:
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
    depends_on:
      - consumer
    entrypoint: python3 producer.py

